nu_oahpa/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^oahpa/i18n/', include('django.conf.urls.i18n')),
    (r'^oahpa/media/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': '/Users/saara/ped/oahpa/media'}),
    (r'^oahpa/dialect/$', 'oahpa.conf.views.dialect'),
    (r'^oahpa/$', 'oahpa.drill.views.oahpa'),
    (r'^oahpa/visl/$', 'oahpa.drill.views.visl'),
    (r'^oahpa/morfa/$', 'oahpa.drill.views.mgame_n'),
    (r'^oahpa/morfa_s/$', 'oahpa.drill.views.mgame_n'),
    (r'^oahpa/morfa_v/$', 'oahpa.drill.views.mgame_v'),
    (r'^oahpa/morfa_a/$', 'oahpa.drill.views.mgame_a'),
    (r'^oahpa/morfa_l/$', 'oahpa.drill.views.mgame_l'),
    (r'^oahpa/cmorfa/$', 'oahpa.drill.views.cmgame_n'),
    (r'^oahpa/morfac/$', 'oahpa.drill.views.cmgame_n'),
    (r'^oahpa/morfac_s/$', 'oahpa.drill.views.cmgame_n'),
    (r'^oahpa/morfac_v/$', 'oahpa.drill.views.cmgame_v'),
    (r'^oahpa/morfac_a/$', 'oahpa.drill.views.cmgame_a'),
    (r'^oahpa/morfac_l/$', 'oahpa.drill.views.cmgame_l'),                       
    (r'^oahpa/leksa/$', 'oahpa.drill.views.quizz'),
    (r'^oahpa/leksa_n/$', 'oahpa.drill.views.quizz_n'),
    (r'^oahpa/numra/$', 'oahpa.drill.views.num'),
    (r'^oahpa/numra_ord/$', 'oahpa.drill.views.num_ord'),
    (r'^oahpa/vasta/$', 'oahpa.drill.views.vasta'),
    (r'^oahpa/sahka/$', 'oahpa.drill.views.sahka'),
    (r'^oahpa/feedback/$', 'oahpa.feedback.views.feedback'), 
        
    # Uncomment this for admin:
    (r'^oahpa/admin/(.*)', admin.site.root),
    (r'^oahpa/courses/', include('oahpa.courses.urls')),
)

nu_oahpa/nu_drill/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Comment(models.Model):
    lang = models.CharField(max_length=5)	
    comment = models.CharField(max_length=100)	
    level = models.CharField(max_length=5)

class Log(models.Model):
    game = models.CharField(max_length=30)
    date = models.DateField(blank=True, null=True)
    userinput = models.CharField(max_length=200)
    iscorrect = models.BooleanField()
    correct = models.CharField(max_length=200)
    example = models.CharField(max_length=200,null=True)
    feedback = models.CharField(max_length=200,null=True)
    comment = models.CharField(max_length=200)

class Semtype(models.Model):
    semtype = models.CharField(max_length=50)

class Source(models.Model):
    type = models.CharField(max_length=20)
    name = models.CharField(max_length=20)

# First, define the Manager subclass.
class NPosManager(models.Manager):
    def get_query_set(self):
        return super(NPosManager, self).get_query_set().filter(pos='N')

class Dialect(models.Model):
    dialect = models.CharField(max_length=5)
    name = models.CharField(max_length=100)

class Word(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    presentationform = models.CharField(max_length=5)
    pos = models.CharField(max_length=5)
    stem = models.CharField(max_length=20)
    valency = models.CharField(max_length=10)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    diphthong=models.CharField(max_length=5)
    gradation=models.CharField(max_length=20)
    rime = models.CharField(max_length=20)
    attrsuffix = models.CharField(max_length=20)
    soggi = models.CharField(max_length=10)
    compare = models.CharField(max_length=5)
# 'translations' should be removed later
#    translations = models.ManyToManyField('Wordnob')
    translations2nob = models.ManyToManyField('Wordnob')
    translations2fin = models.ManyToManyField('Wordfin')
    translations2swe = models.ManyToManyField('Wordswe')
    translations2eng = models.ManyToManyField('Wordeng')
    translations2deu = models.ManyToManyField('Worddeu')
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)
    dialects = models.ManyToManyField(Dialect,null=True)
    objects = models.Manager() # The default manager.
    N_objects = NPosManager() # The Noun-specific manager
    
    
class Wordnob(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    pos = models.CharField(max_length=5)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    translations = models.ManyToManyField(Word)
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)

class Wordfin(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    pos = models.CharField(max_length=5)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    translations = models.ManyToManyField(Word)
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)

class Wordswe(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    pos = models.CharField(max_length=5)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    translations = models.ManyToManyField(Word)
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)

class Wordeng(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    pos = models.CharField(max_length=5)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    translations = models.ManyToManyField(Word)
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)

class Worddeu(models.Model):
    wordid = models.CharField(max_length=200)
    lemma = models.CharField(max_length=200)
    pos = models.CharField(max_length=5)
    semtype = models.ManyToManyField(Semtype)
    source = models.ManyToManyField(Source)
    translations = models.ManyToManyField(Word)
    frequency = models.CharField(max_length=10)
    geography = models.CharField(max_length=10)

class Tagset(models.Model):
    tagset = models.CharField(max_length=25)

class Tagname(models.Model):
    tagname=models.CharField(max_length=25)
    tagset=models.ForeignKey(Tagset)    

class Tag(models.Model):
    string = models.CharField(max_length=25)
    pos = models.CharField(max_length=5)
    case = models.CharField(max_length=5)
    number = models.CharField(max_length=5)
    possessive = models.CharField(max_length=5)
    grade = models.CharField(max_length=10)
    infinite = models.CharField(max_length=10)
    personnumber = models.CharField(max_length=8)
    conneg = models.CharField(max_length=5)
    polarity = models.CharField(max_length=5)
    tense = models.CharField(max_length=5)
    mood = models.CharField(max_length=5)
    subclass = models.CharField(max_length=10)
    attributive = models.CharField(max_length=5)
    class Admin:
        pass

class Form(models.Model):
    word = models.ForeignKey(Word)
    tag = models.ForeignKey(Tag)
    fullform = models.CharField(max_length=200)
    dialects = models.ManyToManyField(Dialect)

########### CONTEXT-MORFA, VASTA

class Question(models.Model):
    qid = models.CharField(max_length=200)
    level = models.IntegerField(max_length=3)
    task = models.CharField(max_length=20)
    string = models.CharField(max_length=200)
    qtype = models.CharField(max_length=20)
    qatype = models.CharField(max_length=20)
    question = models.ForeignKey('self', blank=True, null=True, related_name='answer_set')
    gametype = models.CharField(max_length=5)
    source = models.ManyToManyField(Source)
    
class QElement(models.Model):
    question=models.ForeignKey(Question, null=True)
    syntax = models.CharField(max_length=50)
    identifier = models.CharField(max_length=20)
    gametype = models.CharField(max_length=5)
    agreement = models.ForeignKey('self', blank=True, null=True, related_name='agreement_set')
    tags = models.ManyToManyField(Tag)
    game = models.CharField(max_length=20)
    copy = models.ForeignKey('self', blank=True, null=True, related_name='copy_set')

class WordQElement(models.Model):
    word = models.ForeignKey(Word, null=True)
    qelement = models.ForeignKey(QElement, null=True)
    semtype = models.ForeignKey(Semtype, null=True)

############# MORFA FEEDBACK


class Feedbackmsg(models.Model):
    msgid = models.CharField(max_length=100)

class Feedbacktext(models.Model):
    message = models.CharField(max_length=200)
    language = models.CharField(max_length=6)
    feedbackmsg = models.ForeignKey(Feedbackmsg)


class Feedback(models.Model):
    messages = models.ManyToManyField(Feedbackmsg)
    pos = models.CharField(max_length=5,blank=True,null=True)
    stem = models.CharField(max_length=20,blank=True,null=True)
    diphthong=models.CharField(max_length=5,blank=True,null=True)
    gradation=models.CharField(max_length=15,null=True,blank=True)
    rime = models.CharField(max_length=20,null=True,blank=True)
    soggi = models.CharField(max_length=10,null=True,blank=True)
    case2 = models.CharField(max_length=5,null=True,blank=True)
    number = models.CharField(max_length=5,null=True,blank=True)
    personnumber = models.CharField(max_length=5,null=True,blank=True)
    tense = models.CharField(max_length=5,null=True,blank=True)
    mood = models.CharField(max_length=10,null=True,blank=True)
    grade = models.CharField(max_length=10,null=True,blank=True)
    attrsuffix = models.CharField(max_length=10,null=True,blank=True)
    attributive = models.CharField(max_length=10,null=True,blank=True)
    dialects = models.ManyToManyField(Dialect)
    
    class Meta:
        unique_together = ("pos","stem","diphthong","gradation","rime","soggi","case2","number","personnumber","tense","mood","grade","attrsuffix","attributive")

############ SAHKA
        
class Dialogue(models.Model):
    name = models.CharField(max_length=50,blank=True,null=True)

class Utterance(models.Model):
    utterance = models.CharField(max_length=500,blank=True,null=True)
    utttype = models.CharField(max_length=20,blank=True,null=True)
    links = models.ManyToManyField('LinkUtterance')
    name = models.CharField(max_length=200,blank=True,null=True)
    topic = models.ForeignKey('Topic')
    formlist = models.ManyToManyField(Form)

class UElement(models.Model):
    utterance=models.ForeignKey(Utterance, null=True)
    syntax = models.CharField(max_length=50)
    tag = models.ForeignKey(Tag,null=True,blank=True)

class LinkUtterance(models.Model):
    link = models.ForeignKey(Utterance,null=True,blank=True)
    target = models.CharField(max_length=20,null=True,blank=True)
    variable = models.CharField(max_length=20,null=True,blank=True)
    constant = models.CharField(max_length=20,null=True,blank=True)

class Topic(models.Model):
    topicname = models.CharField(max_length=50,blank=True,null=True)
    dialogue = models.ForeignKey(Dialogue)
    number = models.IntegerField(max_length=3,null=True)
    image = models.CharField(max_length=50,null=True,blank=True)
    formlist = models.ManyToManyField(Form)


######### EXTRA
class Grammarlinks(models.Model):
    name = models.CharField(max_length=200,blank=True,null=True)
    address = models.CharField(max_length=800,blank=True,null=True)
    language = models.CharField(max_length=5,blank=True,null=True)

nu_oahpa/nu_drill/templates/game.html
{% extends "oahpa.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

{% ifnotequal gametype "sahka" %}
<hr/>
{% endifnotequal %}

<table width="100%">
<tr>
<td>

<table>
<tr><td>
<table>
     {% for form in forms %}

{% ifequal settings.gametype 'context' %} 
    {% ifnotequal forloop.counter 1 %}
    <tr>
    <td>&nbsp;</td>
    </tr>
    {% endifnotequal %}
{% endifequal %}
<tr>
{% block question %}{% endblock %}
</tr>

<tr>
  {% if form.answer %}

  <!-- Show correct answers if "show correct" is pressed -->
{% if show_correct %}
  <td> 
    {% if form.answertext1 %}{{ form.answertext1 }}{% endif %}
    {% if form.pron %}
    &nbsp;&nbsp;{{ form.pron }}&nbsp;&nbsp;
    {% endif %}    
    {% ifequal form.error "correct" %}
    <font color="green">{{ form.userans }}</font>
    {% else %}
      {% ifequal form.error "error" %}
       <font color="red">{{ form.userans }}</font>
       {% else %}
       ___________________
      {% endifequal %}
    {% endifequal %}
    {% if form.pron_imp %}
    &nbsp;&nbsp;{{ form.pron_imp }}&nbsp;&nbsp;
    {% endif %}    

    {% if form.answertext2 %}{{ form.answertext2 }}{% endif %}
  </td>

  {% else %}

   <!-- If just test answers, mark correct answers as green -->
  <td>
    {% if form.answertext1 %}{{ form.answertext1 }}{% endif %}
      {% ifnotequal form.userans "" %}
          {% if form.pron %}
	  &nbsp;&nbsp;{{ form.pron }}&nbsp;&nbsp;
	  {% endif %}

        {% ifequal form.error "correct" %}
          <font color="green">{{ form.userans }}</font>
        {% else %}
	  <!-- Answer field -->
	  {{ form.answer }} 
	{% endifequal %}
          {% if form.pron_imp %}
	  &nbsp;&nbsp;{{ form.pron_imp }}&nbsp;&nbsp;
	  {% endif %}

      {% else %}
      <!-- Answer field -->
      {% if form.pron %}
      &nbsp;&nbsp;{{ form.pron }}&nbsp;&nbsp;
      {% endif %}
      {{ form.answer}}
      {% if form.pron_imp %}
      &nbsp;&nbsp;{{ form.pron_imp }}&nbsp;&nbsp;
      {% endif %}
      {% endifnotequal %}
    {% if form.answertext2 %}{{ form.answertext2 }}{% endif %}

     </td>
{% endif %}

    <td align="left">
    {% if show_correct %}
      {% ifnotequal form.error "correct" %}
        {{ form.correct_answers }}
      {% endifnotequal %}
    {% else %}
      {% ifequal form.error "error" %}
      <!-- Feedback -->
          {% if form.feedback %}
	   <div class='popupcontent' id='popup_{{ forloop.counter }}'>{{ form.feedback }}</div>
	   <a href="#" onclick="showPopup(300,150,'popup_{{ forloop.counter }}');" >
      <img width="15" height="15" border="0" src="/oahpa/media/images/error.png"/>
<font color="#093970"><small>{% trans "help" %}</small></font></a>
	  {% else %}
      <img width="15" height="15" border="0" src="/oahpa/media/images/error.png"/>
	  {% endif %}

      {% endifequal %}

	  {% if forloop.last %}
	  {% ifequal gametype "sahka" %}
       </td><td>
      <table width="250px">
	  <tr><td>
	  {% if messages %}
	  <div id="rightbarsahka">
	  {% for m in messages %}{{ m }}<br/>{% endfor %}
	  </div>
	  {% endif %}
      </td></tr></table>
	  {% endifequal %}
	  {% endif %}


  {% endif %}
      </td>
{% endif %}

<td>

 {{ form.word_id }}       {{ form.tag_id }}
{{ form.question_id }} {{ form.answer_id }}       
{{ form.utterance_id }}
{{ form.qstring }} {{ form.astring }}
{% block hidden %}{% endblock %}
<input type="hidden" name="{{ forloop.counter }}-userans" value="{{ form.userans }}" />
<input type="hidden" name="{{ forloop.counter }}-correct" value="{{ form.error }}" />
  {% for detail, value in form.qattrs.items %}
       <input type="hidden" name="{{ forloop.parentloop.counter }}-{{ detail }}" value="{{ value }}" />
  {% endfor %}
  {% for detail, value in form.aattrs.items %}
       <input type="hidden" name="{{ forloop.parentloop.counter }}-{{ detail }}" value="{{ value }}" />
  {% endfor %}

</td>
</tr>
     {% endfor %}

{% block submit %}{% endblock %}

</table>

</td>
</tr>

<tr><td>


{% if score %}
&nbsp;<br/>
{% if all_correct %}
{% trans "Congratulations!" %}
{% endif %}

<br/>
{% trans "Your score:" %} {{ score }}
{% endif %}


{% if comment %}
<br/>
{{ comment }}
{% endif %}

</td>
</tr>

</table>
</td>
{% ifnotequal gametype "sahka" %}
{% ifnotequal gametype "sahka_main" %}
<td width="30%" valign="top">
<table class="instructions" cellpadding="8px">
<tr><td>
{% endifnotequal %}
{% endifnotequal %}

{% block gamename %}{% endblock %}<br/>
{% block instructions %}{% endblock %}

{% ifnotequal gametype "sahka" %}
{% ifnotequal gametype "sahka_main" %}
</td></tr></table></td>
{% endifnotequal %}
{% endifnotequal %}
<td width="10%" valign="top">
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
</table>

{% endblock %}

nu_oahpa/nu_drill/templates/mgame_a.html
{% extends "mgame.html" %}
{% load i18n %}


{% block gamename %}{{ settings.gamename }}{% endblock %}
{% block instructions %}
  {% ifequal settings.gametype "bare" %}
    {% trans "Add adjectives in correct forms. You get translation into Norwegian if you click the word." %}
  {% else %}
    {% trans "Add adjectives in correct forms." %}
  {% endifequal %}
{% endblock %}

{% block selectionname %}
<td>{% trans "Type" %}</td>
  {% ifequal settings.gametype "bare" %}
<td>{% trans "Grade" %}</td>
{% endifequal %}
{% endblock %}

{% block selection %}
  {% ifequal settings.gametype "bare" %}
<td> {{ settingsform.adjcase }} </td>
<td> {{ settingsform.grade }} </td>
  {% else %}
<td> {{ settingsform.adj_context }}</td>
  {% endifequal %}

{% endblock %}

nu_oahpa/nu_drill/templates/mgame_n.html
{% extends "mgame.html" %}
{% load i18n %}


{% block gamename %}{{ settings.gamename }}{% endblock %}
{% block instructions %}
  {% ifequal settings.gametype "bare" %}
    {% trans "Add nouns in correct forms. You get translation if you click the word." %}
  {% else %}
    {% trans "Add nouns in correct forms." %}
  {% endifequal %}
{% endblock %}


{% block selectionname %}<td>{% trans "Case" %}</td>{% endblock %}
{% block selection %}
<td>
  {% ifequal settings.gametype "bare" %}
    {{ settingsform.case }}
  {% else %}
    {{ settingsform.case_context }}
  {% endifequal %}

</td>
{% endblock %}

nu_oahpa/nu_drill/templates/mgame_v.html
{% extends "mgame.html" %}
{% load i18n %}


{% block gamename %}{{ settings.gamename }}{% endblock %}
{% block instructions %}
  {% ifequal settings.gametype "bare" %}
    {% trans "Add verbs in correct forms. You get translation if you click the word." %}
  {% else %}
    {% trans "Add verbs in correct forms." %}
  {% endifequal %}
{% endblock %}


{% block selectionname %}<td>{% trans "Type" %}</td>{% endblock %}
{% block selection %}
<td>
  {% ifequal settings.gametype "bare" %}
    {{ settingsform.vtype }}
  {% else %}
    {{ settingsform.vtype_context }}
  {% endifequal %}

</td>
{% endblock %}

nu_oahpa/nu_drill/templates/num.html
{% extends "game.html" %}
{% load i18n %}

{% block helpaddress %}
{% ifequal LANGUAGE_CODE "no" %}
<a href="http://giellatekno.uit.no/oahpa/numra.nno.html"
{% else %}
<a href="http://giellatekno.uit.no/oahpa/numra.html"
{% endifequal %}
{% endblock %}

{% block navbar %}
<div id="navbar">
<img width="120" height="120" border="0" src="/oahpa/media/images/numra_big.png"/>
<div class="bigheader">NUMRA</div>

<ul class="sidelist">
<li class="selected">{% trans 'Cardinals' %}</li>
<li><a href="/oahpa/numra_ord/">{% trans 'Ordinals' %}</a>
</ul>
</div>
{% endblock %}


{% block name %}{% trans "Numerals" %}{% endblock %}
{% block pagename %}/oahpa/numra/{% endblock %}

{% block gamename %}{% endblock %}
{% block instructions %}
{% endblock %}


{% block settings %}

<table width="700">
<tr>
<td>{% trans "Select the range of numerals." %}</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>{{ settingsform.maxnum }}</td>
<td>{{ settingsform.numgame }}</td>
<td>{{ settingsform.numlanguage }}</td>
<td>&nbsp;</td>
</tr>
</table>
<input type="submit" name="settings" value="{% trans "New set" %}" />
{% endblock %}



{% block question %}
{% if form.numstring %}
<td>{{ form.numstring }} </td>
{% else %}
<td>{{ form.numeral }} </td>
{% endif %}
<td>{{ form.numeral_id }}</td>
{% endblock %}

{% block submit %}
<tr>
<td>
</td>
<td>
{% if not all_correct %}
   {% if not show_correct %}
   <input type="submit" name="test" value="{% trans "Test answers" %}"/>
   {% endif %}
   {% ifequal count 1 %}
   <input type="submit" name="show_correct" value="{% trans "Show correct answers" %}" />
   {% endifequal %}
{% endif %}
</td>
</tr>
{% endblock %}

nu_oahpa/nu_drill/templates/sahka.html
{% extends "game.html" %}
{% load i18n %}

{% block addcss %}
<script type="text/javascript">
function submitSahka(dia) {
   document.gameform.dialogue.value=dia;
   document.gameform.submit();
   return True;
}
</script>
<style type="text/css">

html {
    overflow: scroll;
    height: 100%;
    margin-bottom: 1px;
}

body {
margin:10px 10px 0px 10px;
padding:0px;
background-image: url(/oahpa/media/images/bakgrunn12.jpg);
}

#leftcontent {
position: fixed;
left: 10px;
top: 95px;
width: 180px;
}
#centercontent {
background:white;
margin-left: 179px;
margin-right:9px;
padding: 20px;
border: 1px solid #150517;

font-family: Times;
margin-left: 181px;
margin-right:11px;
margin-bottom: 1px;
}
body #centercontent {
margin-left: 181px;
margin-right:11px;
}
#rightcontent {
position: fixed;
right:10px;
top:95px;
width:120px;
}

#banner {
height:80px;
height:80px;
}
html>body #banner {
height:80px;
}


{% if not forms %}

#centercontent {
background:white;
margin-left: 179px;
margin-right:9px;
padding: 20px;
border: 1px solid #150517;
font-family: Times;
margin-left: 181px;
margin-right:11px;
margin-bottom: 1px;
}
body #centercontent {
margin-left: 181px;
margin-right:11px;
}
{% endif %}
</style>

{% endblock %}

{% block helpaddress %}
{% ifequal LANGUAGE_CODE "no" %}
<a href="http://giellatekno.uit.no/oahpa/sahka.nno.html"
{% else %}
<a href="http://giellatekno.uit.no/oahpa/sahka.html"
{% endifequal %}
{% endblock %}

{% block navbar %}
{% if not forms %}
&nbsp;<br/>
&nbsp;<br/>

<a href="/oahpa/sahka/"><img width="120" height="120" border="0" src="/oahpa/media/images/sahka_big.png"/></a><br/>
<div class="bigheader">SAHKA</div>
<p class="header">{% trans "Select a dialogue" %}</p>

{% endif %}

<!-- Image included from the dialogue -->
{% if image %}
<p>&nbsp;<p>
<center>
<img border="1" width="140" border="0" src="/oahpa/media/images/{{ image }}"/><br/>
</center>
{% endif %}

{% if wordlist %}
<center>
<br/>
<table cellpadding="8px" bgcolor="white" border="1" class="wordlist"><tr><td>{{ wordlist }}</td></tr></table>
</center>
{% endif %}
{% endblock %}

{% block name %}Sahka{% endblock %}
{% block pagename %}/oahpa/sahka/{% endblock %}
{% block settings %}

{% if forms %}
<tr><td>
<!--<p>{% trans "NB! NB! The Sahka game is not working properly, due to technical problems! NB! NB!</p> -->
<p> {% trans "Answer to the questions with full sentences. Remember big initial letter in placenames." %} </p>
<hr/>
</td></tr>
{% endif %}


{% if not forms %}

<table width="700">
<!-- emergency tag starts -->
<tr>
<!--{% trans "NB! NB! The Sahka game is not working properly, due to technical problems! NB! NB!" %} -->
<!--{% trans "NB! NB! The Sahka game is temporarily out of order, due to technical maintenance! NB! NB!" %} -->
</tr>
<!-- emergency tag ends -->
<tr>
<td>
<table cellpadding="10px">
<tr><td>
<input type="hidden" name="dialogue" id="id_dialogue" />
<input type="hidden" name="settings" id="settings" />
<a href="javascript:submitSahka('firstmeeting');">
<img border="0px" width="100"  src="/oahpa/media/images/woman001_small.jpg"/>
{% trans "Meeting with Kare" %}</a>
</td><td>
<a href="javascript:submitSahka('firstmeeting_man');">
<img border="0px" width="108"  src="/oahpa/media/images/man_small.jpg"/>
{% trans "Meeting with Hansa" %}</a>
</td><td>
<a href="javascript:submitSahka('firstmeeting_girl');">
<img border="0px" width="100"  src="/oahpa/media/images/girl_small.jpg"/>
{% trans "Meeting with Lisa" %}</a>
</td><td>
<a href="javascript:submitSahka('firstmeeting_boy');">
<img border="0px" width="100"  src="/oahpa/media/images/boy_small.jpg"/>
{% trans "Meeting with Lemet" %}</a>
</td>
</tr>
</table>
<table cellpadding="10px">
<tr>
<td>
<a href="javascript:submitSahka('visit');">
<img border="0px" width="150" height="200" src="/oahpa/media/images/visit001.jpg"/>
{% trans "Visit" %}</a>
</td>
<td>
<a href="javascript:submitSahka('grocery');">
<img border="0px" width="200" height="150" src="/oahpa/media/images/grocery.jpg"/>
{% trans "Grocery" %}</a>
</td>
<td>
<a href="javascript:submitSahka('shopadj');">
<img border="0px" width="100" src="/oahpa/media/images/2scarves_small.jpg"/><br/>
{% trans "Shop" %}</a>
</td>
</tr>
</table>
</td>
</tr>
</table>

{% endif %}
{% endblock %}

{% block hidden %}
<input type="hidden" name="topicnumber" value="{{ topicnumber }}" />
<input type="hidden" name="num_fields" value="{{ num_fields }}" />
<input type="hidden" name="image" value="{{ image }}" />
<input type="hidden" name="wordlist" value="{{ wordlist }}" />
<input type="hidden" name="gametype" value="sahka" />
<input type="hidden" name="dialogue" value="{{ dialogue }}" />
{% endblock %}

{% block question %}

{% if forms %}
{% if form.utterance %}
<td>{{ form.utterance }}</td>
{% endif %}
{% endif %}
{% endblock %}

{% block submit %}
{% if forms %}
<tr>
<td align="right">
  {% if not all_correct %}
  <input type="submit" id="test" name="test" value="{% trans "Answer" %}"/>
  {% endif %}
</td>

</tr>
{% endif %}

{% endblock %}